version: "2"
services:

  mongo:
    image: mongo:3.2.11
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db
    restart: always

  jenkins:
    image: jenkins:2.19.4-alpine
    ports:
      - "9090:8080"
    volumes:
      - ./data/jenkins:/var/jenkins_home
    restart: always